# Generated by Django 3.1 on 2020-10-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('teacher', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=10)),
            ],
        ),
    ]
